name: solvecase
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+2
  device_info: ^0.4.2+4
  firebase_database: ^3.1.6
  persistent_bottom_nav_bar: ^2.0.5
  fancy_drawer: ^1.0.0
  flutter_switch: ^0.1.1
  ntp: ^1.0.7
  bubble: ^1.1.9+1
  map: ^0.1.0+1
  latlng: ^0.0.2
  firebase_auth: ^0.16.1
  fluttertoast: 4.0.1
  regexed_validator: ^1.0.4
  url_launcher: ^5.4.10
  sqflite: ^1.3.1
  flutter_youtube: ^2.0.0
  cupertino_icons: ^0.1.3
  flutter_share_me: ^0.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Baskervville
      fonts:
        - asset: assets/fonts/Baskervville-Regular.ttf

    - family: Circular
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
